import { FormEvent, useEffect, useState } from 'react';
import { BookOpen, Copy, LogOut, Moon, Plus, Sun, Trash2, Upload, X } from 'lucide-react';
import { api, Book, formatSize } from '../App';

export function Admin({ theme, onTheme }: { theme: string; onTheme: () => void }) { const [auth, setAuth] = useState(sessionStorage.getItem('adminToken')); const [password, setPassword] = useState(''); const [books, setBooks] = useState<Book[]>([]); const [modal, setModal] = useState(false); const [file, setFile] = useState<File>(); const [title, setTitle] = useState(''); const [status, setStatus] = useState('');
  useEffect(() => { if (auth) api('/api/admin/books', { headers: { Authorization: `Bearer ${auth}` } }).then(setBooks).catch(() => setAuth(null)); }, [auth]);
  const login = async (event: FormEvent) => { event.preventDefault(); try { const data = await api('/api/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); sessionStorage.setItem('adminToken', data.token); setAuth(data.token); } catch { setStatus('وشەی نهێنی هەڵەیە'); } };
  const uploadBook = async (event: FormEvent) => { event.preventDefault(); if (!file) return; setStatus('لە بارکردنە...'); const body = new FormData(); body.append('book', file); body.append('title', title || file.name.replace(/\.pdf$/i, '')); try { const book = await api('/api/admin/books', { method: 'POST', headers: { Authorization: `Bearer ${auth}` }, body }); setBooks([...books, book]); setModal(false); setFile(undefined); setTitle(''); setStatus('تەواو بوو'); } catch { setStatus('فایلەکە بار نەکرا'); } };
  const remove = async (id: string) => { if (!confirm('ئەم کتێبە بسڕینەوە؟')) return; await api(`/api/admin/books/${id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${auth}` } }); setBooks(books.filter(book => book.id !== id)); };
  if (!auth) return <main className="login-page"><div className="login-box"><span className="brand-mark"><BookOpen size={22}/></span><h1>بەخێربێیتەوە</h1><p>چوونەژوورەوە بۆ بەڕێوەبردنی کتێبەکان</p><form onSubmit={login}><label>وشەی نهێنی<input type="password" value={password} onChange={e => setPassword(e.target.value)} autoFocus /></label><button className="primary-button" type="submit">چوونەژوورەوە</button></form>{status && <p className="form-error">{status}</p>}</div></main>;
  return <div className="admin-page"><header className="topbar admin-top"><a className="brand" href="/"><span className="brand-mark"><BookOpen size={20}/></span><span><b>بەڕێوەبردن</b><small>Private Book Reader</small></span></a><div className="header-actions"><button className="icon-button" onClick={onTheme}>{theme === 'light' ? <Moon size={18}/> : <Sun size={18}/>}</button><button className="text-button" onClick={() => { sessionStorage.clear(); setAuth(null); }}><LogOut size={16}/> دەرچوون</button></div></header><main className="admin-content"><div className="admin-heading"><div><p className="eyebrow">ناوچەی بەڕێوەبەر</p><h1>کتێبەکانت</h1></div><button className="primary-button" onClick={() => setModal(true)}><Plus size={18}/> زیادکردنی کتێب</button></div>{status && <p className="notice">{status}</p>}<div className="admin-list">{books.map(book => <div className="admin-row" key={book.id}><div className="mini-cover">{book.title.slice(0,1)}</div><div className="row-title"><strong>{book.title}</strong><span>{book.pages || '—'} پەڕە · {formatSize(book.size)}</span></div><span className="complete">تەواو بوو</span><div className="row-actions"><button title="کۆپی لینک" onClick={() => navigator.clipboard?.writeText(`${location.origin}/read/${book.token}`)}><Copy size={17}/></button><a href={`/read/${book.token}`} title="خوێندنەوە"><BookOpen size={17}/></a><button className="danger" title="سڕینەوە" onClick={() => remove(book.id)}><Trash2 size={17}/></button></div></div>)}{!books.length && <div className="empty-state"><Upload size={28}/><h3>هێشتا کتێبت نییە</h3><p>یەکەم PDF ـەکەت بار بکە بۆ دەستپێکردن.</p></div>}</div></main>{modal && <div className="modal-backdrop"><form className="upload-modal" onSubmit={uploadBook}><button type="button" className="modal-close" onClick={() => setModal(false)}><X size={18}/></button><p className="eyebrow">کتێبی نوێ</p><h2>کتێبەکە زیاد بکە</h2><label>ناونیشان<input value={title} onChange={e => setTitle(e.target.value)} placeholder="ناوی کتێب" /></label><label className="drop-zone"><Upload size={28}/><strong>{file ? file.name : 'PDF ـەکە ڕابکێشە بۆ ئێرە'}</strong><span>تەنها فایلەکانی PDF</span><input type="file" accept="application/pdf" onChange={e => setFile(e.target.files?.[0])} /></label><button className="primary-button" disabled={!file}><Upload size={17}/> بارکردنی کتێب</button></form></div>}</div>;
}
