import { useEffect, useState } from 'react';
import { BookOpen, ChevronLeft, Wifi, WifiOff } from 'lucide-react';
import { api, Book, formatSize } from '../App';

export function Library() {
  const [books, setBooks] = useState<Book[]>([]); const [online, setOnline] = useState(navigator.onLine); const [error, setError] = useState('');
  useEffect(() => { const load = async () => { try { const token = location.pathname.split('/')[2]; const data = await api(token ? `/api/public/${token}` : '/api/health'); setBooks(data?.books || []); } catch { setError('کتێبەکان لەم کاتەدا بەردەست نین'); } }; load(); const up = () => setOnline(true); const down = () => setOnline(false); addEventListener('online', up); addEventListener('offline', down); return () => { removeEventListener('online', up); removeEventListener('offline', down); }; }, []);
  return <main className="library-shell"><section className="library-intro"><div><p className="eyebrow">کتێبخانەی تایبەتی</p><h1>هەموو ئەوەی<br/><em>دەخوێنیتەوە.</em></h1><p className="intro-copy">کتێبەکانت بە ئارامی و بێ داگرتنی فایلە گەورەکان بخوێنەوە.</p></div><div className={`connection ${online ? '' : 'offline'}`}>{online ? <Wifi size={16}/> : <WifiOff size={16}/>} {online ? 'پەیوەندی باشە' : 'پەیوەندی نییە'}</div></section><div className="section-head"><h2><BookOpen size={21}/> کتێبەکان</h2><span>{books.length} کتێب</span></div>{error && <p className="notice">{error}</p>}{books.length ? <div className="book-grid">{books.map((book, index) => <BookCard key={book.id} book={book} index={index}/>)}</div> : <div className="empty-state"><BookOpen size={28}/><h3>هێشتا کتێبێک زیاد نەکراوە</h3><p>بەڕێوەبەر دەتوانێت کتێبە تایبەتییەکان زیاد بکات.</p></div>}</main>;
}
function BookCard({ book, index }: { book: Book; index: number }) { const progress = Number(localStorage.getItem(`progress-${book.id}`) || 0); return <article className="book-card" style={{ animationDelay: `${index * 70}ms` }}><div className={`cover cover-${index % 4}`}><span>{book.title.slice(0, 1)}</span><small>کتێبی تایبەتی</small></div><div className="book-info"><span className="book-type">PDF • {book.pages ? `${book.pages} پەڕە` : 'ئامادەی خوێندنەوە'}</span><h3>{book.title}</h3><p>{progress > 0 ? `بەردەوام بە لە پەڕەی ${progress}` : 'هێشتا دەستت پێ نەکردووە'}</p><a className="read-button" href={`/read/${book.token}`}>خوێندنەوە <ChevronLeft size={17}/></a></div></article>; }
