import { useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, Expand, Home, Minus, Moon, Sun, X, ZoomIn } from 'lucide-react';
import { api, Book } from '../App';
import * as pdfjs from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
pdfjs.GlobalWorkerOptions.workerSrc = workerUrl;

export function Reader({ token, theme, onTheme }: { token: string; theme: string; onTheme: () => void }) {
  const [books, setBooks] = useState<Book[]>([]); const [book, setBook] = useState<Book>(); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [scale, setScale] = useState(1); const [error, setError] = useState(''); const [online, setOnline] = useState(navigator.onLine); const [resumePage, setResumePage] = useState(0);
  useEffect(() => { api(`/api/public/${token}`).then(data => { setBooks(data.books); const found = data.books.find((item: Book) => item.token === token); if (!found) throw new Error('book-unavailable'); const savedPage = Number(localStorage.getItem(`progress-${found.id}`) || 1); setBook(found); setPage(savedPage); setResumePage(savedPage > 1 ? savedPage : 0); }).catch(err => setError(err.message === 'invalid-link' ? 'ئەم لینکی خوێندنەوەیە دروست نییە.' : 'ئەم کتێبە بەردەست نییە.')); const up = () => setOnline(true); const down = () => setOnline(false); addEventListener('online', up); addEventListener('offline', down); return () => { removeEventListener('online', up); removeEventListener('offline', down); }; }, [token]);
  useEffect(() => { if (book) localStorage.setItem(`progress-${book.id}`, String(page)); }, [page, book]);
  if (error) return <main className="reader-error"><a href="/"><Home size={18}/> کتێبەکان</a><div><h1>{error}</h1><button className="primary-button" onClick={() => location.reload()}>دووبارە هەوڵبدەوە</button></div></main>;
  if (!book) return <div className="loading-screen"><div className="spinner"/><p>تکایە چاوەڕێ بکە...</p></div>;
  return <div className="reader-page"><header className="reader-bar"><a className="reader-brand" href="/"><Home size={18}/><span>{book.title}</span></a><div className="page-jump"><button onClick={() => setPage(Math.max(1, page - 1))} disabled={page <= 1}><ChevronRight size={19}/> پەڕەی پێشوو</button><strong>پەڕەی {page} <small>/ {total || book.pages || '...'}</small></strong><button onClick={() => setPage(Math.min(total || book.pages || page + 1, page + 1))}><پChevronLeft /></button></div><div className="reader-actions"><button onClick={() => setScale(Math.min(2, scale + .15))} title="گەورەکردنەوە"><ZoomIn size={18}/></button><button onClick={() => setScale(Math.max(.6, scale - .15))} title="بچووککردنەوە"><Minus size={18}/></button><button onClick={() => document.documentElement.requestFullscreen?.()} title="شاشەی تەواو"><Expand size={18}/></button><button onClick={onTheme}>{theme === 'light' ? <Moon size={18}/> : <Sun size={18}/>}</button></div></header>{resumePage > 0 && <div className="resume-note"><span>لە پەڕەی {resumePage} وەستابوویت · ئێستا لەوێ بەردەوام بە</span><button onClick={() => setResumePage(0)} title="داخستن"><X size={16}/></button></div>}<div className="reader-body"><aside className="book-drawer"><h3>کتێبەکان</h3>{books.map(item => <a className={item.id === book.id ? 'active' : ''} href={`/read/${item.token}`} key={item.id}>{item.title}</a>)}</aside><PdfViewport book={book} page={page} scale={scale} onPageCount={setTotal} onPage={setPage} online={online}/></div></div>;
}
function PdfViewport({ book, page, scale, onPageCount, onPage, online }: { book: Book; page: number; scale: number; onPageCount: (n: number) => void; onPage: (n: number) => void; online: boolean }) { const host = useRef<HTMLDivElement>(null); const touchStart = useRef<number | undefined>(undefined); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false);
  useEffect(() => { let cancelled = false; setLoading(true); setFailed(false); pdfjs.getDocument({ url: `/api/books/${book.id}/read?token=${encodeURIComponent(book.token)}`, rangeChunkSize: 65536, disableAutoFetch: true, disableStream: false }).promise.then(async doc => { if (cancelled) return; onPageCount(doc.numPages); const pages = [page - 1, page, page + 1].filter(n => n >= 1 && n <= doc.numPages); if (host.current) host.current.replaceChildren(); for (const pageNumber of pages) { const pdfPage = await doc.getPage(pageNumber); if (cancelled || !host.current) return; const viewport = pdfPage.getViewport({ scale: scale * Math.min(1.2, (host.current.clientWidth - 36) / pdfPage.getViewport({ scale: 1 }).width) }); const canvas = document.createElement('canvas'); canvas.className = pageNumber === page ? 'pdf-page current' : 'pdf-page nearby'; canvas.width = viewport.width; canvas.height = viewport.height; canvas.dataset.page = String(pageNumber); host.current.appendChild(canvas); await pdfPage.render({ canvas, canvasContext: canvas.getContext('2d')!, viewport }).promise; } setLoading(false); }).catch(() => { if (!cancelled) { setFailed(true); setLoading(false); } }); return () => { cancelled = true; }; }, [book, page, scale, onPageCount]);
  return <section className="pdf-stage" onTouchStart={event => { touchStart.current = event.touches[0].clientX; }} onTouchEnd={event => { const start = touchStart.current; const end = event.changedTouches[0].clientX; if (start === undefined || Math.abs(end - start) < 50) return; if (end < start) onPage(Math.min(page + 1, book.pages || page + 1)); else onPage(Math.max(1, page - 1)); touchStart.current = undefined; }}>{!online && <div className="offline-banner">پەیوەندی ئینتەرنێت لاوازە، تکایە چاوەڕێ بکە...</div>}{loading && <div className="page-loading"><div className="spinner"/><span>پەڕەکە ئامادە دەکرێت...</span></div>}{failed ? <div className="page-loading">نەتوانرا کتێبەکە بکرێتەوە.</div> : <div ref={host} className="pdf-pages"/>}<div className="stage-controls"><button onClick={() => onPage(Math.max(1, page - 1))}><ChevronRight/></button><span>{page}</span><button onClick={() => onPage(Math.min(book.pages || page + 1, page + 1))}><ChevronLeft/></button></div></section>;
}
const پChevronLeft = () => <ChevronLeft size={19}/>;
